
platform :ios, '13.0'

target 'Visitor' do
    use_frameworks!

pod 'FBSDKCoreKit' 
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'GoogleAnalytics'
pod 'InterfaceBuilderKit'
pod 'DLRadioButton', '~> 1.4'
pod 'GoogleAnalytics'
pod 'Parse'
pod 'Firebase'
pod 'FirebaseABTesting'
pod 'FirebaseAuth'
pod 'FirebaseCore'
pod 'FirebaseDatabase'
pod 'FirebaseFirestore'
pod 'FirebaseFunctions'
pod 'FirebaseMessaging'
pod 'Firebase/RemoteConfig'
pod 'FirebaseStorage'
pod 'Fabric'
pod 'FirebaseFirestoreSwift'
pod 'CountryList'
pod 'Charts'
pod 'ChartsRealm'
pod 'PromiseKit/QuartzCore'
pod 'GoogleInterchangeUtilities'
pod 'GoogleNetworkingUtilities'
pod 'GoogleParsingUtilities'
pod 'GoogleSymbolUtilities'
pod 'GoogleUtilities'
pod 'Crashlytics'
pod "Yoga"  
pod 'React'
pod 'Google-Mobile-Ads-SDK'
end